<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [45]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [46]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [47]:
pd.set_option('display.max_columns', 200)
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [48]:
# Write your code here
print('Comlumn data types:\n', df.dtypes)
print('\nDF counts:\n', df.info())
print('\nMissing values count:\n', df.isna().sum())

Comlumn data types:
 ResponseId                          int64
MainBranch                         object
Age                                object
Employment                         object
RemoteWork                         object
Check                              object
CodingActivities                   object
EdLevel                            object
LearnCode                          object
LearnCodeOnline                    object
TechDoc                            object
YearsCode                          object
YearsCodePro                       object
DevType                            object
OrgSize                            object
PurchaseInfluence                  object
BuyNewTool                         object
BuildvsBuy                         object
TechEndorse                        object
Country                            object
Currency                           object
CompTotal                         float64
LanguageHaveWorkedWith             object
LanguageWantToWorkWith             object
LanguageAdmired                    object
DatabaseHaveWorkedWith             object
DatabaseWantToWorkWith             object
DatabaseAdmired                    object
PlatformHaveWorkedWith             object
PlatformWantToWorkWith             object
PlatformAdmired                    object
WebframeHaveWorkedWith             object
WebframeWantToWorkWith             object
WebframeAdmired                    object
EmbeddedHaveWorkedWith             object
EmbeddedWantToWorkWith             object
EmbeddedAdmired                    object
MiscTechHaveWorkedWith             object
MiscTechWantToWorkWith             object
MiscTechAdmired                    object
ToolsTechHaveWorkedWith            object
ToolsTechWantToWorkWith            object
ToolsTechAdmired                   object
NEWCollabToolsHaveWorkedWith       object
NEWCollabToolsWantToWorkWith       object
NEWCollabToolsAdmired              object
OpSysPersonal use                  object
OpSysProfessional use              object
OfficeStackAsyncHaveWorkedWith     object
OfficeStackAsyncWantToWorkWith     object
OfficeStackAsyncAdmired            object
OfficeStackSyncHaveWorkedWith      object
OfficeStackSyncWantToWorkWith      object
OfficeStackSyncAdmired             object
AISearchDevHaveWorkedWith          object
AISearchDevWantToWorkWith          object
AISearchDevAdmired                 object
NEWSOSites                         object
SOVisitFreq                        object
SOAccount                          object
SOPartFreq                         object
SOHow                              object
SOComm                             object
AISelect                           object
AISent                             object
AIBen                              object
AIAcc                              object
AIComplex                          object
AIToolCurrently Using              object
AIToolInterested in Using          object
AIToolNot interested in Using      object
AINextMuch more integrated         object
AINextNo change                    object
AINextMore integrated              object
AINextLess integrated              object
AINextMuch less integrated         object
AIThreat                           object
AIEthics                           object
AIChallenges                       object
TBranch                            object
ICorPM                             object
WorkExp                           float64
Knowledge_1                        object
Knowledge_2                        object
Knowledge_3                        object
Knowledge_4                        object
Knowledge_5                        object
Knowledge_6                        object
Knowledge_7                        object
Knowledge_8                        object
Knowledge_9                        object
Frequency_1                        object
Frequency_2                        object
Frequency_3                        object
TimeSearching                      object
TimeAnswering                      object
Frustration                        object
ProfessionalTech                   object
ProfessionalCloud                  object
ProfessionalQuestion               object
Industry                           object
JobSatPoints_1                    float64
JobSatPoints_4                    float64
JobSatPoints_5                    float64
JobSatPoints_6                    float64
JobSatPoints_7                    float64
JobSatPoints_8                    float64
JobSatPoints_9                    float64
JobSatPoints_10                   float64
JobSatPoints_11                   float64
SurveyLength                       object
SurveyEase                         object
ConvertedCompYearly               float64
JobSat                            float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

DF counts:
 None

Missing values count:
 ResponseId                            0
MainBranch                            0
Age                                   0
Employment                            0
RemoteWork                        10631
Check                                 0
CodingActivities                  10971
EdLevel                            4653
LearnCode                          4949
LearnCodeOnline                   16200
TechDoc                           24540
YearsCode                          5568
YearsCodePro                      13827
DevType                            5992
OrgSize                           17957
PurchaseInfluence                 18031
BuyNewTool                        20256
BuildvsBuy                        22079
TechEndorse                       21769
Country                            6507
Currency                          18753
CompTotal                         31697
LanguageHaveWorkedWith             5692
LanguageWantToWorkWith             9685
LanguageAdmired                   14565
DatabaseHaveWorkedWith            15183
DatabaseWantToWorkWith            22879
DatabaseAdmired                   26880
PlatformHaveWorkedWith            23071
PlatformWantToWorkWith            30905
PlatformAdmired                   34060
WebframeHaveWorkedWith            20276
WebframeWantToWorkWith            26902
WebframeAdmired                   30494
EmbeddedHaveWorkedWith            43223
EmbeddedWantToWorkWith            47837
EmbeddedAdmired                   48704
MiscTechHaveWorkedWith            25994
MiscTechWantToWorkWith            32473
MiscTechAdmired                   35841
ToolsTechHaveWorkedWith           12955
ToolsTechWantToWorkWith           19353
ToolsTechAdmired                  21440
NEWCollabToolsHaveWorkedWith       7845
NEWCollabToolsWantToWorkWith      13350
NEWCollabToolsAdmired             14726
OpSysPersonal use                  7263
OpSysProfessional use             12464
OfficeStackAsyncHaveWorkedWith    17344
OfficeStackAsyncWantToWorkWith    26471
OfficeStackAsyncAdmired           28233
OfficeStackSyncHaveWorkedWith      9892
OfficeStackSyncWantToWorkWith     18726
OfficeStackSyncAdmired            20725
AISearchDevHaveWorkedWith         20984
AISearchDevWantToWorkWith         28736
AISearchDevAdmired                29894
NEWSOSites                         5151
SOVisitFreq                        5901
SOAccount                          5877
SOPartFreq                        20200
SOHow                              6475
SOComm                             6274
AISelect                           4530
AISent                            19564
AIBen                             28543
AIAcc                             28135
AIComplex                         28416
AIToolCurrently Using             30365
AIToolInterested in Using         34746
AIToolNot interested in Using     41023
AINextMuch more integrated        51999
AINextNo change                   52939
AINextMore integrated             41009
AINextLess integrated             63082
AINextMuch less integrated        64289
AIThreat                          20748
AIEthics                          23889
AIChallenges                      27906
TBranch                           20960
ICorPM                            35636
WorkExp                           35779
Knowledge_1                       36773
Knowledge_2                       37416
Knowledge_3                       37342
Knowledge_4                       37407
Knowledge_5                       37557
Knowledge_6                       37573
Knowledge_7                       37659
Knowledge_8                       37679
Knowledge_9                       37802
Frequency_1                       37068
Frequency_2                       37073
Frequency_3                       37727
TimeSearching                     36526
TimeAnswering                     36593
Frustration                       37186
ProfessionalTech                  37673
ProfessionalCloud                 36946
ProfessionalQuestion              36630
Industry                          36579
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_6                    35987
JobSatPoints_7                    35989
JobSatPoints_8                    35981
JobSatPoints_9                    35981
JobSatPoints_10                   35987
JobSatPoints_11                   35992
SurveyLength                       9255
SurveyEase                         9199
ConvertedCompYearly               42002
JobSat                            36311
dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [50]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [51]:
# Write your code here
print('Number of unique countries:', df['Country'].nunique())
print('\nTop 10 Countries:\n', df['Country'].value_counts().head(10))
print('\nBottom 10 Countries:\n', df['Country'].value_counts().tail(10))

Number of unique countries: 185

Top 10 Countries:
 Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Name: count, dtype: int64

Bottom 10 Countries:
 Country
Niger                                 1
Guinea                                1
Saint Kitts and Nevis                 1
Lesotho                               1
Haiti                                 1
Micronesia, Federated States of...    1
Nauru                                 1
Chad                                  1
Djibouti                              1
Solomon Islands                       1
Name: count, dtype: int64

In [52]:
pd.set_option('display.max_rows', 200)
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Turkey                                                    546
Belgium                                                   526
Denmark                                                   504
Portugal                                                  470
Norway                                                    450
Romania                                                   439
Pakistan                                                  415
Iran, Islamic Republic of...                              411
China                                                     406
Mexico                                                    402
New Zealand                                               396
Hungary                                                   396
Greece                                                    389
Finland                                                   386
South Africa                                              358
Indonesia                                                 354
Argentina                                                 345
Bangladesh                                                327
Bulgaria                                                  319
Nigeria                                                   305
Viet Nam                                                  296
Japan                                                     288
Ireland                                                   270
Taiwan                                                    268
Egypt                                                     262
Slovakia                                                  248
Serbia                                                    245
Colombia                                                  217
Philippines                                               196
Croatia                                                   187
Lithuania                                                 183
Kenya                                                     180
Singapore                                                 177
Sri Lanka                                                 163
Malaysia                                                  161
Thailand                                                  147
South Korea                                               146
Hong Kong (S.A.R.)                                        146
Slovenia                                                  142
Nepal                                                     139
Chile                                                     133
United Arab Emirates                                      130
Latvia                                                    128
Estonia                                                   110
Morocco                                                    98
Belarus                                                    97
Georgia                                                    94
Uruguay                                                    94
Kazakhstan                                                 81
Algeria                                                    77
Peru                                                       75
Tunisia                                                    71
Ghana                                                      70
Venezuela, Bolivarian Republic of...                       69
Cyprus                                                     63
Bosnia and Herzegovina                                     62
Uzbekistan                                                 62
Ethiopia                                                   60
Armenia                                                    58
Republic of Korea                                          57
Afghanistan                                                56
Saudi Arabia                                               56
Costa Rica                                                 54
Ecuador                                                    54
Albania                                                    49
Dominican Republic                                         47
Lebanon                                                    46
Kyrgyzstan                                                 44
Iraq                                                       44
Nomadic                                                    43
Guatemala                                                  41
Luxembourg                                                 40
Jordan                                                     40
Uganda                                                     39
Paraguay                                                   39
Republic of Moldova                                        38
Republic of North Macedonia                                36
Bolivia                                                    32
Iceland                                                    31
Cameroon                                                   31
Syrian Arab Republic                                       30
Malta                                                      29
United Republic of Tanzania                                28
Montenegro                                                 27
Azerbaijan                                                 27
Zimbabwe                                                   26
Cuba                                                       23
Rwanda                                                     22
Cambodia                                                   22
Myanmar                                                    21
Nicaragua                                                  21
Angola                                                     20
El Salvador                                                19
Kosovo                                                     18
Yemen                                                      18
Panama                                                     18
Maldives                                                   16
Honduras                                                   16
Mauritius                                                  15
Palestine                                                  15
Andorra                                                    15
Qatar                                                      15
Zambia                                                     15
Madagascar                                                 14
Côte d'Ivoire                                              14
Isle of Man                                                13
Malawi                                                     12
Jamaica                                                    11
Turkmenistan                                               11
Benin                                                      11
Bahrain                                                    11
Mongolia                                                   10
Somalia                                                     9
Senegal                                                     9
Togo                                                        9
Kuwait                                                      8
Congo, Republic of the...                                   8
Trinidad and Tobago                                         8
Oman                                                        8
Mozambique                                                  7
Tajikistan                                                  7
Sudan                                                       7
Barbados                                                    6
Suriname                                                    5
Cape Verde                                                  5
Botswana                                                    5
Antigua and Barbuda                                         5
Namibia                                                     5
Mauritania                                                  5
Lao People's Democratic Republic                            4
Liechtenstein                                               4
Fiji                                                        4
Gabon                                                       4
Bahamas                                                     4
Swaziland                                                   4
Burkina Faso                                                4
Liberia                                                     4
Libyan Arab Jamahiriya                                      4
San Marino                                                  3
Sierra Leone                                                3
Democratic Republic of the Congo                            3
Burundi                                                     3
Bhutan                                                      3
Monaco                                                      3
Guyana                                                      3
North Korea                                                 3
Brunei Darussalam                                           3
Democratic People's Republic of Korea                       2
Mali                                                        2
Guinea-Bissau                                               2
Belize                                                      2
Dominica                                                    1
Papua New Guinea                                            1
Equatorial Guinea                                           1
Central African Republic                                    1
Samoa                                                       1
Niger                                                       1
Guinea                                                      1
Saint Kitts and Nevis                                       1
Lesotho                                                     1
Haiti                                                       1
Micronesia, Federated States of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [53]:
## Write your code here
country_replacement = {
    'United States of America' : 'USA',
    'United Kingdom of Great Britain and Northern Ireland' : 'UK',
    'Iran, Islamic Republic of...' : 'Iran',
    'Venezuela, Bolivarian Republic of...' : 'Venezuela',
    'Viet Nam' : 'Vietnam',
    'Republic of Korea' : 'South Korea',
    'Democratic People\'s Republic of Korea' : 'North Korea',
    'Congo, Republic of the...' : 'Republic of Congo',
    'Nomadic' : 'np.nan'
}

df['Country'] = df['Country'].replace(country_replacement)
df['Country'].unique()

array(['USA', 'UK', 'Canada', 'Norway', 'Uzbekistan', 'Serbia', 'Poland',
       'Philippines', 'Bulgaria', 'Switzerland', 'India', 'Germany',
       'Ireland', 'Italy', 'Ukraine', 'Australia', 'Brazil', 'Japan',
       'Austria', 'Iran', 'France', 'Saudi Arabia', 'Romania', 'Turkey',
       'Nepal', 'Algeria', 'Sweden', 'Netherlands', 'Croatia', 'Pakistan',
       'Czech Republic', 'Republic of North Macedonia', 'Finland',
       'Slovakia', 'Russian Federation', 'Greece', 'Israel', 'Belgium',
       'Mexico', 'United Republic of Tanzania', 'Hungary', 'Argentina',
       'Portugal', 'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon',
       'Spain', 'South Africa', 'Lithuania', 'Vietnam',
       'Dominican Republic', 'Indonesia', 'Kosovo', 'Morocco', 'Taiwan',
       'Georgia', 'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria',
       'Liechtenstein', 'Denmark', 'Ecuador', 'Malaysia', 'Albania',
       'Azerbaijan', 'Chile', 'Ghana', 'Peru', 'Bolivia', 'Egypt',
       'Luxembourg', 'Montenegro', 'Cyprus', 'Paraguay', 'Kazakhstan',
       'Slovenia', 'Jordan', 'Venezuela', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'South Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic of Moldova', 'Isle of Man', 'np.nan',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'Iceland', 'Honduras', 'Hong Kong (S.A.R.)',
       "Lao People's Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic of the Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "Côte d'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad and Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra', 'Qatar', 'Sudan', 'Cameroon',
       'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi', 'Burkina Faso',
       'Republic of Congo', 'Botswana', 'Guinea-Bissau', 'Mozambique',
       'Central African Republic', 'Equatorial Guinea', 'Suriname',
       'Belize', 'Libyan Arab Jamahiriya', 'Cape Verde',
       'Brunei Darussalam', 'Bhutan', 'Guinea', 'Niger',
       'Antigua and Barbuda', 'Mali', 'Samoa', 'Lesotho',
       'Saint Kitts and Nevis', 'Monaco',
       'Micronesia, Federated States of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [54]:
df['Employment'].unique()

array(['Employed, full-time', 'Student, full-time',
       'Student, full-time;Not employed, but looking for work',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, and not looking for work',
       'Employed, full-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Student, full-time', 'Employed, part-time',
       'Student, full-time;Employed, part-time',
       'Student, part-time;Employed, part-time', 'I prefer not to say',
       'Not employed, but looking for work', 'Student, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Student, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Student, full-time;Not employed, and not looking for work',
       'Retired',
       'Independent contractor, freelancer, or self-employed;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Not employed, but looking for work;Student, part-time',
       'Not employed, but looking for work;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Retired',
       'Not employed, but looking for work;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Not employed, and not looking for work',
       'Employed, full-time;Not employed, but looking for work',
       'Student, full-time;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Not employed, and not looking for work;Student, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Student, full-time;Student, part-time',
       'Student, full-time;Not employed, but looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Student, full-time;Student, part-time',
       'Not employed, but looking for work;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work',
       'Not employed, and not looking for work;Retired',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired',
       'Employed, full-time;Not employed, but looking for work;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Student, full-time;Not employed, but looking for work;Retired',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Student, part-time;Retired',
       'Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Retired',
       'Employed, full-time;Student, full-time;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Employed, full-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Retired',
       'Student, full-time;Student, part-time;Employed, part-time',
       'Employed, part-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Employed, full-time;Student, part-time;Employed, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Student, full-time;Student, part-time;Retired',
       'Student, full-time;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Not employed, but looking for work;Student, part-time;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Student, part-time',
       'Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired'],
      dtype=object)

In [55]:
## Write your code here
# encoded_employment = pd.get_dummies(df['Employment'], prefix = 'Employment')

# df = pd.concat([df, encoded_employment], axis=1)
# df.head(10)

employment_split_encoded = df['Employment'].str.get_dummies(sep=';')

# 2. Clean up the resulting column names (strip whitespace) and add a prefix for clarity.
employment_split_encoded.columns = ['Employment_' + col.strip() for col in employment_split_encoded.columns]

# 3. Concatenate the new encoded columns back to the main DataFrame
df = pd.concat([df, employment_split_encoded], axis=1)

# 4. Drop the original 'Employment' column
#df.drop('Employment', axis=1, inplace=True)

df.head(10)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,"Employment_Employed, full-time","Employment_Employed, part-time",Employment_I prefer not to say,"Employment_Independent contractor, freelancer, or self-employed","Employment_Not employed, and not looking for work","Employment_Not employed, but looking for work",Employment_Retired,"Employment_Student, full-time","Employment_Student, part-time"
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,UK,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,UK,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN,1,0,0,0,0,0,0,0,0
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN,0,0,0,0,0,0,0,1,0
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN,0,0,0,0,0,0,0,1,0
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,NaN,10,NaN,Student,NaN,NaN,NaN,NaN,NaN,USA,NaN,NaN,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Cloud Firestore,Cloud Firestore,Cloud Firestore,Cloudflare,Cloudflare,Cloudflare,Node.js,Node.js,Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NaN,NaN,NaN,Docker;Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,iOS;MacOS;Ubuntu,NaN,Markdown File,Markdown File,Markdown File,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help,Documenting code;Testing code;Committing and r...,Learning about a codebase;Project planning,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN,0,0,0,0,0,0,0,1,0
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,NaN,7,7,Academic researcher,NaN,NaN,NaN,NaN,NaN,USA,NaN,NaN,R,R,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RStudio,RStudio,RStudio,MacOS,MacOS,NaN,NaN,NaN,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN,1,0,0,0,0,0,0,0,0
7,8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,First-party knowledge base,1,NaN,Student,NaN,NaN,NaN,NaN,NaN,Uzbekistan,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,Supabase,Supabase,Supabase,Firebase;Netlify;Vercel,Vercel,Vercel,Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Vite;Yarn,npm;Vite,npm;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Jira,NaN,NaN,Google Meet;Telegram;Zoom,Google Meet;Telegram,Google Meet;Telegram,ChatGPT,ChatGPT,ChatGPT,Stack Overflow,Less than once per month or monthly,No,NaN,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Indifferent,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Bad at handling complex tasks,Writing code;Debugging and getting help;Search...,Project planning;Testing code,NaN,NaN,NaN,Writing code;Debugging and getting help;Search...,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN,0,0,0,0,0,1,0,1,0
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,NaN,20,NaN,Academic researcher,NaN,NaN,NaN,NaN,NaN,UK,NaN,NaN,Lua,Lua,Lua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,NaN,NaN,NaN,Skype,Skype,Skype,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Engage with community by commenting on questio...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN,1,0,0,0,0,0,0,0,0
9,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,Traditional public search engine;AI-powered se...,15,11,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Serbia,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Windows,Jira,Jira,Jira,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Increase productivity;Speed up learning,Neither trust nor distrust,Bad at handling complex tasks,Search for answers,NaN,NaN,NaN,Search for answers,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN,0,0,0,1,0,0,0,0,0

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [56]:
## Write your code here
df.isna().sum().idxmax()

'AINextMuch less integrated'

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [57]:
df['ConvertedCompYearly'].isna().sum()

np.int64(42002)

In [58]:
## Write your code here
comp_mean = df['ConvertedCompYearly'].mean()

df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(comp_mean)

df['ConvertedCompYearly'].isna().sum()

np.int64(0)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [59]:
## Write your code here
remote_mode = df['RemoteWork'].mode()[0]

df['RemoteWork'] = df['RemoteWork'].fillna(remote_mode)

df['RemoteWork'].isna().sum()

np.int64(0)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [60]:
## Write your code here
comp_min = df['ConvertedCompYearly'].min()
comp_max = df['ConvertedCompYearly'].max()

df['ConvertedCompYearly_MinMax'] = ((df['ConvertedCompYearly'] - comp_min) / (comp_max - comp_min))

df['ConvertedCompYearly_MinMax'].head(20)

0     0.0053
1     0.0053
2     0.0053
3     0.0053
4     0.0053
5     0.0053
6     0.0053
7     0.0053
8     0.0053
9     0.0053
10    0.0053
11    0.0053
12    0.0053
13    0.0053
14    0.0053
15    0.0053
16    0.0053
17    0.0053
18    0.0053
19    0.0053
Name: ConvertedCompYearly_MinMax, dtype: float64

In [61]:
print("Max Value: ", comp_max)
print("Min Value: ", comp_min)

Max Value:  16256603.0
Min Value:  1.0

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [63]:
## Write your code here
import numpy as np

# Natural log
#df['ConvertedCompYearly_LofTransform'] = np.log1p(df['ConvertedCompYearly'])

# log of 1 plus the value: for better handing 0 values
df['ConvertedCompYearly_LogTransform'] = np.log1p(df['ConvertedCompYearly'])

df['ConvertedCompYearly_LogTransform'].head()

0    11.363918
1    11.363918
2    11.363918
3    11.363918
4    11.363918
Name: ConvertedCompYearly_LogTransform, dtype: float64

In [64]:
df[['ConvertedCompYearly', 'ConvertedCompYearly_MinMax', 'ConvertedCompYearly_LogTransform']].head(10)

,ConvertedCompYearly,ConvertedCompYearly_MinMax,ConvertedCompYearly_LogTransform
0,86155.287263,0.0053,11.363918
1,86155.287263,0.0053,11.363918
2,86155.287263,0.0053,11.363918
3,86155.287263,0.0053,11.363918
4,86155.287263,0.0053,11.363918
5,86155.287263,0.0053,11.363918
6,86155.287263,0.0053,11.363918
7,86155.287263,0.0053,11.363918
8,86155.287263,0.0053,11.363918
9,86155.287263,0.0053,11.363918

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [66]:
df['YearsCodePro'].value_counts()

YearsCodePro
2                     4168
3                     4093
5                     3526
10                    3251
4                     3215
Less than 1 year      2856
6                     2843
1                     2639
8                     2549
7                     2517
12                    1777
15                    1635
20                    1549
9                     1493
11                    1312
13                    1127
14                    1082
25                     998
16                     946
18                     867
17                     814
30                     689
24                     632
19                     516
22                     492
23                     448
26                     426
27                     380
21                     380
28                     342
35                     285
29                     196
40                     194
32                     194
34                     169
38                     134
33                     132
36                     119
31                     106
37                     104
45                      56
42                      55
39                      54
41                      51
More than 50 years      50
44                      42
43                      37
46                      21
50                      14
48                      14
49                      11
47                      10
Name: count, dtype: int64

In [67]:
## Write your code here

# Junior: Less than 3 years of professional experience.
# Mid-Level: 3 to 10 years of professional experience.
# Senior/Expert: More than 10 years of professional experience.

df['YearsCodePro'].replace({'Less than 1 year' : 0.5, 'More than 50 years' : 51}, inplace = True)

df['YearsCodePro_Cleaned'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')`

bins = [0, 3, 10, df['YearsCodePro_Cleaned'].max() + 1]
labels = ['Junior', 'Mid-Level', 'Senior']

df['ExperienceLevel'] = pd.cut(
    df['YearsCodePro_Cleaned'], bins = bins, label = labels, right = False
)

df['ExperienceLevel'].value_counts()

/tmp/ipykernel_300/2740494317.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['YearsCodePro'].replace({'Less than 1 year' : 0.5, 'More than 50 years' : 51}, inplace = True)

TypeError: '>=' not supported between instances of 'float' and 'str'

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.